### PR TITLE
add test for MicroTimer

### PR DESCRIPTION
**Pull request by shomagan**
Running with arguments for the MicroTimer test, for example
      api-chrono-test -execute_all -micro_timer
      procces does not start with debugging information
      12001819062: 29.2: 804A1D0 - CRITICAL - Heap error
temporarily make -microtimer

### CODE REVIEW

**Comment by tyler-gilbert** [comment]
@shomagan I will see if I can recreate the issue.

**Comment by tyler-gilbert** [comment]
@shomagan This is a bug that has been fixed, I will update the kernel for your board.

**Comment by tyler-gilbert** [comment]
@shomagan I published a new BSP (v0.10) for the Nucleo429 board. Please install it and let me know if it fixes the issue.

**Comment by shomagan** [comment]
Yes works

**Pull request merged**
